-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('FREE', 'OPERATOR_CONTRACT', 'PAYMENT_CARD', 'CASH', 'PREPAID_CARD', 'FLEET_CARD', 'BANK_TRANSFER', 'ONLINE_PAYMENT', 'UNDETERMINED');

-- CreateEnum
CREATE TYPE "AuthMethod" AS ENUM ('OPEN_ACCESS', 'NO_ACCESS', 'RFID_MIFARE_CLASSIC', 'RFID_MIFARE_DESFIRE', 'RFID_CALYPSO', 'PINPAD', 'MOBILE_APP', 'PHONE_RFID', 'ISO15118_PLC', 'ISO15118_WIRELESS', 'PHONE_VOICE', 'SMS', 'PREPAID_CARD');

-- AlterTable
ALTER TABLE "ChargingOperator" ADD COLUMN     "paymentMethodCoverage" JSONB;

-- AlterTable
ALTER TABLE "ChargingStation" ADD COLUMN     "acceptedPaymentMethods" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "authenticationTypes" TEXT[] DEFAULT ARRAY[]::TEXT[];
